language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

notifications:
  email:
    recipients:
      - kroslakma@gmail.com
    on_success: change
    on_failure: always
