[package]
name = "vk-parse"
version = "0.1.0"
authors = ["krolli <kroslakma@gmail.com>"]
description = "Vulkan specification parser"
readme = "README.md"
license = "Apache-2.0/MIT"
keywords = ["vulkan", "parser"]
categories = ["parser-implementations", "rendering::graphics-api"]

[dependencies]
vkxml = "0.3"
xml-rs = "0.8"
ron = "0.3"
clap = "2"
serde = "1"
serde_derive = "1"

[dev-dependencies]
reqwest = "*"
serde-xml-rs = {git = "https://github.com/RReverser/serde-xml-rs.git"}

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/krolli/vk-parse/" }
is-it-maintained-open-issues = { repository = "https://github.com/krolli/vk-parse/" }
