[package]
name = "vk-parse"
version = "0.1.0"
authors = ["krolli <kroslakma@gmail.com>"]

[dependencies]
vkxml = {git = "https://github.com/terrybrashaw/vkxml"}
xml-rs = "*"
ron = "*"
serde-xml-rs = {git = "https://github.com/RReverser/serde-xml-rs.git"}
clap = "*"
serde = "*"
serde_derive = "*"

[dev-dependencies]
reqwest = "*"
